### PR TITLE
Healthcheck checks all hosts if multiple added with AddHost

### LINKED ISSUE #1710: Health check for multiple hosts should not return on the first failing host
My suggestion is that health check should not return on the first failing host, but try all other hosts registered with AddHost and return a message with all failing hosts. FolderHeathCheck returns a error description for each missing folders

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.System/FolderHealthCheck.cs#LL26C9-L26C9

Most of the other HealthCheck e.g.

- Ping https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.Network/PingHealthCheck.cs#LL28C28-L28C28
- TCP https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.Network/TcpHealthCheck.cs#L32
- SSL https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.Network/SslHealthCheck.cs#L42

return the erro on the first failing host. Therefore if multiple hosts fail than only one is reported. It would be nice if all healthchecks that have the AddHost method to add multiple hosts support the error message construction like FolderHeathCheck does.

For now the workaround is to use multple time AddPingHealthCheck, AddTcpHealthCheck, ...

### PR DESCRIPTION
**Pull request by michaelmairegger**
Modify some health checks in such a way that they will not return failure state on first failing host but continue with other hosts. This allows to view the state of all hosts, if others are failing

This is a preview of what I wanted to point out with the opened issue. If this work is OK, then I will continue for other health-checks and add further commits to this PR

Closes #1710

### CODE REVIEW

**Comment by sungam3r** [comment]
I think that for all checks that check several entities (folders, hosts, drives, etc), it makes sense to add an option like `CheckAllDrives` by analogy with one from `DiskStorageOptions`.

**Comment by michaelmairegger** [comment]
@sungam3r  done

**Comment by sungam3r** [comment]
Conflicts here.

> If you want I can continue for other checks too?

OK.

File: src/HealthCheckResultTask.cs [hunk 1]
```diff
@@ -10,3 +10,27 @@ internal static class HealthCheckResultTask
     /// </summary>
     public static readonly Task<HealthCheckResult> Healthy = Task.FromResult(HealthCheckResult.Healthy());
 }
+
```
Comment (sungam3r) [inline src/HealthCheckResultTask.cs:13]:
```suggestion
```

File: src/HealthCheckResultTask.cs [hunk 2]
```diff
@@ -10,3 +10,26 @@ internal static class HealthCheckResultTask
...
+    public Task<HealthCheckResult> GetHealthStateAsync(HealthCheckContext context)
+    {
+        if (Count > 0)
+        {
+            return Task.FromResult(new HealthCheckResult(context.Registration.FailureStatus, description: string.Join("; ", this)));
+        }
+
+        return HealthCheckResultTask.Healthy;
+    }
+
```
Comment (sungam3r) [inline src/HealthCheckResultTask.cs:25]:
```suggestion
```

Comment (sungam3r) [reply src/HealthCheckResultTask.cs:25]: Also I would switch to extension method for `List<string>` so insteaf of `return errorList?.GetHealthState(context) ?? HealthCheckResult.Healthy();` you can write `return errorList.GetHealthState(context);`

File: src/HealthCheckResultTask.cs [hunk 3]
```diff
@@ -10,3 +10,15 @@ internal static class HealthCheckResultTask
     /// </summary>
     public static readonly Task<HealthCheckResult> Healthy = Task.FromResult(HealthCheckResult.Healthy());
 }
+
+internal static class StringListExtensions
+{
+    public static HealthCheckResult GetHealthState(this List<string> instance, HealthCheckContext context)
+    {
+        if (instance.Count == 0)
```
Comment (sungam3r) [inline src/HealthCheckResultTask.cs:18]:
```suggestion
    public static HealthCheckResult GetHealthState(this List<string>? instance, HealthCheckContext context)
    {
        if (instance?.Count ?? 0 == 0)
```

File: src/HealthChecks.Network/DnsResolveHealthCheck.cs [hunk 4]
```diff
@@ -20,6 +20,7 @@ public async Task<HealthCheckResult> CheckHealthAsync(HealthCheckContext context
     {
         try
         {
+            List<string> errorList = new();
```
Comment (sungam3r) [inline src/HealthChecks.Network/DnsResolveHealthCheck.cs:23]:
```suggestion
            List<string>? errorList = null;

```

File: src/HealthChecks.Network/DnsResolveHealthCheck.cs [hunk 5]
```diff
@@ -32,12 +33,16 @@ public async Task<HealthCheckResult> CheckHealthAsync(HealthCheckContext context
                 {
                     if (item.Resolutions == null || !item.Resolutions.Contains(ipAddress.ToString()))
                     {
-                        return new HealthCheckResult(context.Registration.FailureStatus, description: $"Ip Address {ipAddress} was not resolved from host {item.Host}");
+                        errorList.Add($"Ip Address {ipAddress} was not resolved from host {item.Host}");
```
Comment (sungam3r) [inline src/HealthChecks.Network/DnsResolveHealthCheck.cs:36]:
```suggestion
                        (errorList ??= new()).Add($"Ip Address {ipAddress} was not resolved from host {item.Host}");

```

Comment (sungam3r) [reply src/HealthChecks.Network/DnsResolveHealthCheck.cs:36]: I would avoid memory allocations for green path.

Comment (michaelmairegger) [reply src/HealthChecks.Network/DnsResolveHealthCheck.cs:36]: Do you mean, that errorList should only be initialized if there is an error?

File: src/HealthCheckResultTask.cs (hunk 3 above)
Comment (michaelmairegger) [reply src/HealthCheckResultTask.cs:18]: Doesn't it look strange if the GetHealthState method works on `null` objects? Writing the suggested code will allow the following code:

```
List<string>? t = null;
if (t is null)
{
    t.GetHealthState(context);
}
```

Code is valid and works but this is weird.

File: src/HealthChecks.Network/DnsResolveHealthCheck.cs (hunk 5 above)
Comment (michaelmairegger) [reply src/HealthChecks.Network/DnsResolveHealthCheck.cs:36]:
```
public static class EmptyList<T>
{
    internal static readonly List<T> Value = new List<T>();
}
```

And initialize it with

`List<string> errorList = EmptyList<string>.Value;`

With this helper class no additional memory is allocated.

Comment (sungam3r) [reply src/HealthChecks.Network/DnsResolveHealthCheck.cs:36]: > Do you mean, that errorList should only be initialized if there is an error?

Yes.

> With this helper class no additional memory is allocated.

It does not work. Static instance will be used by all checks concurrently.

File: src/HealthCheckResultTask.cs (hunk 3 above)
Comment (sungam3r) [reply src/HealthCheckResultTask.cs:18]: > Doesn't it look strange if the GetHealthState method works on null objects? 

In our case - no, because `null` means the _no errors_.

**Comment by michaelmairegger** [comment]
Don't know what those failing tests mean.

**Comment by sungam3r** [comment]
They mean that your PR changed public API surface. Each test project has *.approved.txt file that tracks public APIs. Open your IDE for tests, navigate to particular `ApiApprovalTests` test and run it. It will generate `*.received.txt` file in case of changes. Delete approved (old one) and rename received to approved.

**Comment by sungam3r** [comment]
Thanks.
